- name: ceph cluster status
  shell: ceph health
  ignore_errors: yes
  register: ceph_cluster_status

- name: Create {{ceph_user_keydir}} directory
  file:
    path: "{{ceph_user_keydir}}"
    state: directory
  run_once: true

- name: copy user key
  copy:
    src: ceph_userkey/
    dest: "{{ceph_user_keydir}}"
    owner: root
    group: root
    mode: "0644"
  run_once: true

- name: get glance user
  shell: ceph auth get-key client.glance
  ignore_errors: yes
  register: glance_user  
  when: ceph_cluster_status.stdout == "HEALTH_OK"
  run_once: true

- name: create glance user
  shell: ceph auth import -i client.glance
  args:
    chdir: "{{ceph_user_keydir}}" 
  when: glance_user.rc != 0
  run_once: true
  
#- name: create glance user
#  shell: ceph auth get-or-create client.glance mon 'profile rbd' osd 'profile rbd pool={{pools[1].values()[0]["name"]}}' -o {{ceph_user_keydir}}/ceph.client.glance.keyring
#  when: glance_user.rc != 0
#  run_once: true

- name: get cinder user
  shell: ceph auth get-key client.cinder
  ignore_errors: yes
  register: cinder_user
  when: ceph_cluster_status.stdout == "HEALTH_OK"
  run_once: true

- name: create cinder user
  shell: ceph auth import -i client.cinder
  args:
    chdir: "{{ceph_user_keydir}}" 
  when: cinder_user.rc != 0
  run_once: true
  
#- name: create cinder user
#  shell: ceph auth get-or-create client.cinder mon 'profile rbd' osd 'profile rbd pool={{pools[0].values()[0]["name"]}}, profile rbd pool={{pools[3].values()[0]["name"]}}, profile rbd pool={{pools[1].values()[0]["name"]}}' -o {{ceph_user_keydir}}/ceph.client.cinder.keyring
#  when: cinder_user.rc != 0
#  run_once: true

- name: get cinder-backup user
  shell: ceph auth get-key client.cinder-backup
  ignore_errors: yes
  register: cinder_backup_user
  when: ceph_cluster_status.stdout == "HEALTH_OK"
  run_once: true

- name: create cinder-backup user
  shell: ceph auth import -i client.cinder-backup
  args:
    chdir: "{{ceph_user_keydir}}" 
  when: cinder_backup_user.rc != 0
  run_once: true

#- name: create cinder-backup user
#  shell: ceph auth get-or-create client.cinder-backup mon 'profile rbd' osd 'profile rbd pool={{pools[3].values()[0]["name"]}}' -o {{ceph_user_keydir}}/ceph.client.cinder-backup.keyring
#  when: cinder_backup_user.rc != 0
#  run_once: true
