- name: Add ceph repository
  template:
    src: ceph-local.repo
    dest: /etc/yum.repos.d/ceph.repo
    owner: root
    group: root
  when: "(install_yum_mode) == 'local'"

- name: Add ceph repository
  template:
    src: ceph.repo
    dest: /etc/yum.repos.d/ceph.repo
    owner: root
    group: root
  when: "(install_yum_mode) == 'aliyun'"

- name: yum update cache
  yum:
    update_cache: yes
    state: present

- name: authentication key generation 
  shell: ssh-keygen -q -N "" -f /root/.ssh/id_rsa
  args:
    creates: /root/.ssh/id_rsa
  connection: local
  run_once: true

- name: Set authorized key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    exclusive: yes

- name: copy private key 
  copy:
    src: /root/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: '0400'

- name: add known_hosts
  template:
    src: /root/.ssh/known_hosts
    dest: /root/.ssh/known_hosts

- name: copy ssh config
  copy:
    src: config
    dest: /root/.ssh/config

- name: install ceph-deploy
  yum:
    name: ceph-deploy
    state: present
  when: ansible_hostname == (ceph_admin)

- name: install ceph package
  yum:
    name:
      - ceph
      - snappy 
    state: present
